version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: zaqroot
      MYSQL_USER: user
      MYSQL_PASSWORD: zaquser
