version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3360:3306
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: golang
